-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;



DROP DATABASE IF EXISTS qa;

CREATE DATABASE qa;
-- ---
-- Table 'questions'
--
-- ---

--connect to DB with
\c qa;

--Drop tables

DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS photos CASCADE;



CREATE TABLE questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INTEGER NOT NULL, --will be a secondary index
  question_body VARCHAR(1000) NOT NULL,
  question_date BIGINT NOT NULL,
  asker_name VARCHAR(60) NOT NULL,
  asker_email VARCHAR(60) NOT NULL,
  reported BOOLEAN NOT NULL DEFAULT FALSE,
  question_helpfulness INT NOT NULL DEFAULT 0
);


--CREATE TEMP TABLE FOR AUTO INCREMENTING
CREATE TEMP TABLE tmp AS SELECT * FROM questions LIMIT 0;

COPY tmp FROM '/home/changerbang/projects/team-clefable/questions.csv' DELIMITER ',' CSV HEADER;

INSERT INTO questions (product_id, question_body, question_date, asker_name, asker_email, reported, question_helpfulness) SELECT product_id, question_body, question_date, asker_name, asker_email, reported, question_helpfulness FROM tmp;
-- ---
-- Table 'answers'
--
-- ---


CREATE TABLE answers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  question_id INTEGER NULL,
  body VARCHAR(1000) NOT NULL,
  date BIGINT NOT NULL,
  answerer_name VARCHAR(60) NOT NULL,
  answerer_email VARCHAR(60) NOT NULL,
  reported BOOLEAN NOT NULL DEFAULT FALSE,
  helpfulness INTEGER NOT NULL DEFAULT 0
);

--diary temp table
CREATE TEMP TABLE tmp1 AS SELECT * FROM answers LIMIT 0;

COPY tmp1 FROM '/home/changerbang/projects/team-clefable/answers.csv' DELIMITER ',' CSV HEADER;

INSERT INTO answers (question_id, body, date, answerer_name, answerer_email, reported, helpfulness) SELECT question_id, body, date, answerer_name, answerer_email, reported, helpfulness FROM tmp1;


-- ---
-- Table 'photos'
--
-- ---


CREATE TABLE photos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  answers_id INTEGER NOT NULL,
  url VARCHAR NOT NULL
);


CREATE TEMP TABLE tmp2 AS SELECT * FROM photos LIMIT 0;

COPY tmp2 FROM '/home/changerbang/projects/team-clefable/answers_photos.csv' DELIMITER ',' CSV HEADER;

INSERT INTO photos (answers_id, url) SELECT answers_id, url FROM tmp2;
-- ---
-- Table 'product'
--
-- ---

-- DROP TABLE IF EXISTS product;

-- CREATE TABLE product (
--   id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
--   name VARCHAR NOT NULL,
--   slogan VARCHAR NOT NULL,
--   description VARCHAR NOT NULL,
--   category INTEGER NOT NULL,
--   default_price INTEGER NOT NULL
-- );

-- ---
-- Foreign Keys
-- ---

ALTER TABLE answers ADD CONSTRAINT question_id_fk FOREIGN KEY (question_id) REFERENCES questions (id);
-- ALTER TABLE questions ADD CONSTRAINT product_id_fk FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE photos ADD CONSTRAINT answers_id_fk  FOREIGN KEY (answers_id) REFERENCES answers (id);

--COPY DATA FROM CSV INTO TABLES

-- \COPY questions FROM '/home/changerbang/projects/team-clefable/questions.csv' DELIMITER ',' CSV HEADER;

-- \COPY answers FROM '/home/changerbang/projects/team-clefable/answers.csv' DELIMITER ',' CSV HEADER;

-- \COPY photos FROM '/home/changerbang/projects/team-clefable/answers_photos.csv' DELIMITER ',' CSV HEADER;



-- SELECT SETVAL((SELECT PG_GET_SERIAL_SEQUENCE('questions', 'id')), (SELECT (MAX('id') + 1) FROM ('questions'), FALSE);

-- select setval('questions_id_seq', select max(id) from questions);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `answers` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `questions` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `photos` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `product` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
