-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;



DROP DATABASE IF EXISTS qa;

CREATE DATABASE qa;
-- ---
-- Table 'questions'
--
-- ---

--connect to DB with
\c qa;

DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS photos CASCADE;



CREATE TABLE questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INTEGER NOT NULL, --will be a secondary index
  question_body VARCHAR(1000) NOT NULL,
  question_date BIGINT NOT NULL,
  asker_name VARCHAR(60) NOT NULL,
  asker_email VARCHAR(60) NOT NULL,
  reported BOOLEAN NOT NULL DEFAULT FALSE,
  question_helpfulness INT NOT NULL DEFAULT 0
);


-- ---
-- Table 'answers'
--
-- ---


CREATE TABLE answers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  question_id INTEGER NULL,
  body VARCHAR(1000) NOT NULL,
  date BIGINT NOT NULL,
  answerer_name VARCHAR(60) NOT NULL,
  answerer_email VARCHAR(60) NOT NULL,
  reported BOOLEAN NOT NULL DEFAULT FALSE,
  helpfulness INTEGER NOT NULL DEFAULT 0
);


-- ---
-- Table 'photos'
--
-- ---


CREATE TABLE photos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  answers_id INTEGER NOT NULL,
  url VARCHAR NOT NULL
);

-- ---
-- Table 'product'
--
-- ---

-- DROP TABLE IF EXISTS product;

-- CREATE TABLE product (
--   id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
--   name VARCHAR NOT NULL,
--   slogan VARCHAR NOT NULL,
--   description VARCHAR NOT NULL,
--   category INTEGER NOT NULL,
--   default_price INTEGER NOT NULL
-- );

-- ---
-- Foreign Keys
-- ---

ALTER TABLE answers ADD CONSTRAINT question_id_fk FOREIGN KEY (question_id) REFERENCES questions (id);
-- ALTER TABLE questions ADD CONSTRAINT product_id_fk FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE photos ADD CONSTRAINT answers_id_fk  FOREIGN KEY (answers_id) REFERENCES answers (id);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `answers` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `questions` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `photos` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `product` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ---
-- Test Data
-- ---

-- INSERT INTO `answers` (`id`,`body`,`date_written`,`answerer_name`,`answerer_email`,`reported`,`helpful`,`photos`,`question_id`) VALUES
-- ('','','','','','','','','');
-- INSERT INTO `questions` (`id`,`body`,`date_written`,`asker_name`,`asker_email`,`helpful`,`reported`,`product_id`) VALUES
-- ('','','','','','','','');
-- INSERT INTO `photos` (`id`,`url`,`answers_id`) VALUES
-- ('','','');
-- INSERT INTO `product` (`id`,`name`,`slogan`,`description`,`category`,`default_price`) VALUES
-- ('','','','','','');